cc_library(
    name = "commandLine",
    srcs = ["commandLine.cpp"],
    hdrs = ["commandLine.h"],
    copts = [
		"-Iclient/commanLine/processCommandLine/",
	],
	deps = [
		"//client/commanLine/processCommandLine:processCommandLineLib",
	]
)