cc_library(
	name = "syncClientInfo",
	srcs = [
		"syncClientInfo.cpp",
	],
	hdrs = [
		"syncClientInfo.h",
	],
	deps = [
		"//mylib/mylibLog:myLibLog",
		"//mylib/enum:myLibEnum",
		"//mylib/mylibSql:myLibSqlApi",
	],
	visibility = ["//visibility:public"],
)