cc_library(
	name = "receiveMessage",
	srcs = [
		"receiveMessage.cpp",
	],
	hdrs = [
		"receiveMessage.h",
	],
	deps = [
		"//mylib/mylibLog:myLibLog",
		"//protos/proto:message_receiver_cc_grpc",
	],
	visibility = ["//visibility:public"],
)