cc_binary (
	name = "userLoginManagerService",
	srcs = ["main.cpp"],
	copts = [
		"-Imylib/myLibIni",
		"-Iserver/service",
	],
	deps = [
		"//mylib/myLibIni:myLibIni",
		"//server/service:userLoginManageService",
	],

)
