cc_library(
	name = "myLibIni",
	srcs = [
		"ConvertUTF.cc",
	],
	hdrs = [
		"ConvertUTF.h",
		"simpleIni.h",
	],
	copts = [
		"-Imylib/mylibLog",
	],
	deps = [
		"//mylib/mylibLog:myLibLog",
	],
	visibility = ["//visibility:public"],
)